service:
  name: vocabuilder-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  tableName: 'words-${opt:stage}'

provider:
  name: aws
  runtime: nodejs8.10
  profile: serverless-aws-admin
  region: us-east-1

  # iamRoleStatements to set the permissions for Lambda to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    WORDS_TABLE: ${self:custom.tableName}
  
resources:
  Resources:
    WordsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: wordId
            AttributeType: S
          - AttributeName: userId 
            AttributeType: S
        KeySchema:
          - AttributeName: wordId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        

functions:
  createWord:
    handler: src/modules/words/create.main
    events:
      - http:
          path: words
          method: post
          cors: true
          authorizer: aws_iam
  getWord:
    handler: src/modules/words/getWord.main
    events:
      - http:
          path: words/{id}
          method: get
          cors: true
          authorizer: aws_iam
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
